name : 'Commit PR Title'

on :
  pull_request :
    types : [ opened, edited, synchronize, reopened ]

jobs :
  check-pr-title :
    name : Check PR Title
    runs-on : ubuntu-latest
    steps :
      - uses : deepakputhraya/action-pr-title@master
        with :
          regex : '^(feat|fix|docs|style|refactor|perf|test|chore|build|ci)(.+?)?: .+' # Regex the title should match.
          allowed_prefixes : 'feat,fix,docs,style,refactor,perf,test,chore,build,ci' # title should start with the given prefix
          prefix_case_sensitive : true
          min_length : 6
          max_length : 220
          github_token : ${{ github.token }} # Default: ${{ github.token }}
